// To run seed use
// npm run seed

// Data has been generated by AI to save time

import bcrypt from "bcryptjs";
import { prisma } from "../src/lib/prisma.js";
import * as prismaEnums from "../generated/prisma/enums.js";

import type {
  User,
  Resource,
  Activity,
  Group,
  Post,
} from "../generated/prisma/client.js";

// Helper functions

// Safely retrieves an item from an array.
function getItem<T>(array: T[], index: number): T {
  const item = array[index];

  if (item === undefined) {
    throw new Error(`Expected an item at index ${index}, but none was found.`);
  }

  return item;
}

// Creates deterministic UUIDs for seed data.
// This allows the seed to be safely executed multiple times.
function seedUuid(prefix: string, index: number): string {
  return `${prefix}-0000-4000-8000-${String(index).padStart(12, "0")}`;
}

// Seeds the data

async function main() {
  console.log("🌱 Starting database seed...\n");

  // ============================================================
  // PASSWORDS
  // ============================================================

  // For demonstration purposes, all regular users share one password.
  const adminPswd = await bcrypt.hash("Admin123", 10);
  const usrPswd = await bcrypt.hash("User123", 10);

  // ============================================================
  // USERS
  // ============================================================

  console.log("🌱 Creating users...");

  const admin = await prisma.user.upsert({
    where: {
      email: "admin@mindharbor.com",
    },
    update: {
      password: adminPswd,
      role: prismaEnums.UserRole.ADMINISTRATOR,
    },
    create: {
      email: "admin@mindharbor.com",
      password: adminPswd,
      role: prismaEnums.UserRole.ADMINISTRATOR,
      username: "admin",
      firstName: "Alex",
      lastName: "Administrateur",
      bio: "Administrateur système de MindHarbor.",
      visibilityLevel: prismaEnums.UserVisibilityLevel.PUBLIC,
      privateMessageLevel: prismaEnums.UserPrivateMessageLevel.TOUT_LE_MONDE,
    },
  });

  const usersData = [
    {
      email: "sophie.martin@mindharbor.local",
      username: "sophie_m",
      firstName: "Sophie",
      lastName: "Martin",
      bio: "Intéressée par la pleine conscience et le développement personnel.",
      visibilityLevel: prismaEnums.UserVisibilityLevel.PRIVE,
      privateMessageLevel: prismaEnums.UserPrivateMessageLevel.PERSONNE,
    },
    {
      email: "thomas.gagnon@mindharbor.local",
      username: "thomas_g",
      firstName: "Thomas",
      lastName: "Gagnon",
      bio: "Essaie d'améliorer sa routine de sommeil.",
      visibilityLevel: prismaEnums.UserVisibilityLevel.PUBLIC,
      privateMessageLevel: prismaEnums.UserPrivateMessageLevel.TOUT_LE_MONDE,
    },
    {
      email: "emma.roy@mindharbor.local",
      username: "emma_roy",
      firstName: "Emma",
      lastName: "Roy",
      bio: "Apprend à mieux gérer le stress quotidien.",
      visibilityLevel: prismaEnums.UserVisibilityLevel.GROUPES_SEULEMENT,
      privateMessageLevel:
        prismaEnums.UserPrivateMessageLevel.MEMBRES_DE_MES_GROUPES,
    },
    {
      email: "lucas.tremblay@mindharbor.local",
      username: "lucas_t",
      firstName: "Lucas",
      lastName: "Tremblay",
      bio: "Ici pour partager ses expériences et soutenir les autres.",
      visibilityLevel: prismaEnums.UserVisibilityLevel.PRIVE,
      privateMessageLevel: prismaEnums.UserPrivateMessageLevel.PERSONNE,
    },
    {
      email: "chloe.bouchard@mindharbor.local",
      username: "chloe_b",
      firstName: "Chloé",
      lastName: "Bouchard",
      bio: "Intéressée par les relations saines et la communication.",
      visibilityLevel: prismaEnums.UserVisibilityLevel.PUBLIC,
      privateMessageLevel: prismaEnums.UserPrivateMessageLevel.TOUT_LE_MONDE,
    },
    {
      email: "gabriel.leblanc@mindharbor.local",
      username: "gabriel_l",
      firstName: "Gabriel",
      lastName: "Leblanc",
      bio: "Travaille à maintenir un meilleur équilibre entre sa vie professionnelle et personnelle.",
      visibilityLevel: prismaEnums.UserVisibilityLevel.GROUPES_SEULEMENT,
      privateMessageLevel:
        prismaEnums.UserPrivateMessageLevel.MEMBRES_DE_MES_GROUPES,
    },
    {
      email: "lea.fortin@mindharbor.local",
      username: "lea_f",
      firstName: "Léa",
      lastName: "Fortin",
      bio: "Aime écrire dans son journal et lire.",
      visibilityLevel: prismaEnums.UserVisibilityLevel.PUBLIC,
      privateMessageLevel: prismaEnums.UserPrivateMessageLevel.TOUT_LE_MONDE,
    },
    {
      email: "nathan.beaulieu@mindharbor.local",
      username: "nathan_b",
      firstName: "Nathan",
      lastName: "Beaulieu",
      bio: "Essaie différentes techniques pour réduire son stress.",
      visibilityLevel: prismaEnums.UserVisibilityLevel.PRIVE,
      privateMessageLevel: prismaEnums.UserPrivateMessageLevel.PERSONNE,
    },
    {
      email: "camille.girard@mindharbor.local",
      username: "camille_g",
      firstName: "Camille",
      lastName: "Girard",
      bio: "Intéressée par le sommeil, la pleine conscience et le bien-être.",
      visibilityLevel: prismaEnums.UserVisibilityLevel.PUBLIC,
      privateMessageLevel: prismaEnums.UserPrivateMessageLevel.TOUT_LE_MONDE,
    },
  ];

  const users: User[] = [];

  for (const userData of usersData) {
    const user = await prisma.user.upsert({
      where: {
        email: userData.email,
      },
      update: {
        username: userData.username,
        firstName: userData.firstName,
        lastName: userData.lastName,
        bio: userData.bio,
        visibilityLevel: userData.visibilityLevel,
        privateMessageLevel: userData.privateMessageLevel,
      },
      create: {
        email: userData.email,
        password: usrPswd,
        role: prismaEnums.UserRole.USER,
        username: userData.username,
        firstName: userData.firstName,
        lastName: userData.lastName,
        bio: userData.bio,
        visibilityLevel: userData.visibilityLevel,
        privateMessageLevel: userData.privateMessageLevel,
      },
    });

    users.push(user);
  }

  const allUsers: User[] = [admin, ...users];

  console.log(`🌱 ${allUsers.length} users created/updated successfully`);

  // ============================================================
  // ACTIVITIES
  // ============================================================

  console.log("🌱 Creating activities...");

  const activityData = [
    {
      name: "Méditation",
      desc: "Un exercice de pleine conscience axé sur la relaxation et la prise de conscience.",
    },
    {
      name: "Marche",
      desc: "Une promenade relaxante pour prendre l'air et faire une activité physique légère.",
    },
    {
      name: "Exercice de respiration",
      desc: "Un exercice de respiration guidé conçu pour favoriser la relaxation.",
    },
    {
      name: "Lecture",
      desc: "Lire un livre ou un article comme activité relaxante.",
    },
    {
      name: "Journal",
      desc: "Écrire ses pensées, ses émotions et ses expériences.",
    },
    {
      name: "Étirements",
      desc: "Des étirements doux pour détendre le corps et réduire les tensions.",
    },
  ];

  const activities: Activity[] = [];

  for (const data of activityData) {
    const activity = await prisma.activity.upsert({
      where: {
        name: data.name,
      },
      update: {
        desc: data.desc,
      },
      create: data,
    });

    activities.push(activity);
  }

  console.log(
    `🌱 ${activities.length} activities created/updated successfully`,
  );

  // ============================================================
  // RESOURCES
  // ============================================================

  console.log("🌱 Creating resources...");

  const resourceData = [
    // ANXIETY
    {
      name: "Comprendre l'anxiété",
      category: prismaEnums.ResourceCategory.ANXIETY,
      type: prismaEnums.ResourceType.ARTICLE,
      duration: 10,
      level: 1,
    },
    {
      name: "Exercice de respiration simple",
      category: prismaEnums.ResourceCategory.ANXIETY,
      type: prismaEnums.ResourceType.EXERCICE,
      duration: 5,
      level: 1,
    },
    {
      name: "Gérer les inquiétudes quotidiennes",
      category: prismaEnums.ResourceCategory.ANXIETY,
      type: prismaEnums.ResourceType.FICHE_PRATIQUE,
      duration: 15,
      level: 2,
    },
    {
      name: "Ressources d'aide sur l'anxiété",
      category: prismaEnums.ResourceCategory.ANXIETY,
      type: prismaEnums.ResourceType.LIEN_EXTERNE,
      duration: 10,
      level: 1,
    },

    // SLEEP
    {
      name: "Comprendre l'hygiène du sommeil",
      category: prismaEnums.ResourceCategory.SLEEP,
      type: prismaEnums.ResourceType.ARTICLE,
      duration: 12,
      level: 1,
    },
    {
      name: "Exercice de relaxation du soir",
      category: prismaEnums.ResourceCategory.SLEEP,
      type: prismaEnums.ResourceType.EXERCICE,
      duration: 10,
      level: 1,
    },
    {
      name: "Créer une meilleure routine de sommeil",
      category: prismaEnums.ResourceCategory.SLEEP,
      type: prismaEnums.ResourceType.FICHE_PRATIQUE,
      duration: 20,
      level: 2,
    },
    {
      name: "Ressources éducatives sur le sommeil",
      category: prismaEnums.ResourceCategory.SLEEP,
      type: prismaEnums.ResourceType.LIEN_EXTERNE,
      duration: 15,
      level: 1,
    },

    // RELATIONSHIP
    {
      name: "Communication saine",
      category: prismaEnums.ResourceCategory.RELATIONSHIP,
      type: prismaEnums.ResourceType.ARTICLE,
      duration: 15,
      level: 1,
    },
    {
      name: "Exercice d'écoute active",
      category: prismaEnums.ResourceCategory.RELATIONSHIP,
      type: prismaEnums.ResourceType.EXERCICE,
      duration: 10,
      level: 1,
    },
    {
      name: "Établir des limites saines",
      category: prismaEnums.ResourceCategory.RELATIONSHIP,
      type: prismaEnums.ResourceType.FICHE_PRATIQUE,
      duration: 20,
      level: 2,
    },
    {
      name: "Ressources d'aide sur les relations",
      category: prismaEnums.ResourceCategory.RELATIONSHIP,
      type: prismaEnums.ResourceType.LIEN_EXTERNE,
      duration: 10,
      level: 1,
    },

    // WORK
    {
      name: "Comprendre le stress au travail",
      category: prismaEnums.ResourceCategory.WORK,
      type: prismaEnums.ResourceType.ARTICLE,
      duration: 12,
      level: 1,
    },
    {
      name: "Prendre des pauses efficaces",
      category: prismaEnums.ResourceCategory.WORK,
      type: prismaEnums.ResourceType.EXERCICE,
      duration: 5,
      level: 1,
    },
    {
      name: "Gérer sa charge de travail",
      category: prismaEnums.ResourceCategory.WORK,
      type: prismaEnums.ResourceType.FICHE_PRATIQUE,
      duration: 20,
      level: 2,
    },
    {
      name: "Ressources sur l'équilibre travail-vie personnelle",
      category: prismaEnums.ResourceCategory.WORK,
      type: prismaEnums.ResourceType.LIEN_EXTERNE,
      duration: 10,
      level: 1,
    },

    // GRIEF
    {
      name: "Comprendre le deuil",
      category: prismaEnums.ResourceCategory.GRIEF,
      type: prismaEnums.ResourceType.ARTICLE,
      duration: 15,
      level: 1,
    },
    {
      name: "Trouver des moments de calme",
      category: prismaEnums.ResourceCategory.GRIEF,
      type: prismaEnums.ResourceType.EXERCICE,
      duration: 10,
      level: 1,
    },
    {
      name: "Faire face à une perte",
      category: prismaEnums.ResourceCategory.GRIEF,
      type: prismaEnums.ResourceType.FICHE_PRATIQUE,
      duration: 20,
      level: 2,
    },
    {
      name: "Organismes d'aide au deuil",
      category: prismaEnums.ResourceCategory.GRIEF,
      type: prismaEnums.ResourceType.LIEN_EXTERNE,
      duration: 15,
      level: 1,
    },
  ];

  const resources: Resource[] = [];

  for (const data of resourceData) {
    const resource = await prisma.resource.upsert({
      where: {
        name: data.name,
      },
      update: {
        category: data.category,
        type: data.type,
        duration: data.duration,
        level: data.level,
      },
      create: data,
    });

    resources.push(resource);
  }

  console.log(`🌱 ${resources.length} resources created/updated successfully`);

  // ============================================================
  // GROUPS
  // ============================================================

  console.log("🌱 Creating groups...");

  const groupData = [
    {
      name: "Soutien contre l'anxiété",
      theme: "Gestion de l'anxiété",
      desc: "Une communauté de soutien pour discuter de l'anxiété et du stress quotidien.",
      rules:
        "Soyez respectueux. Ne jugez pas les autres membres. Respectez la vie privée de chacun.",
      visibility: prismaEnums.GroupVisibility.PUBLIC,
    },
    {
      name: "Meilleur sommeil",
      theme: "Sommeil et repos",
      desc: "Une communauté pour discuter des habitudes de sommeil, des routines et de la relaxation.",
      rules:
        "Partagez vos expériences avec respect. Ne présentez pas vos expériences personnelles comme des conseils médicaux.",
      visibility: prismaEnums.GroupVisibility.PUBLIC,
    },
    {
      name: "Cercle de soutien privé",
      theme: "Bien-être général",
      desc: "Une petite communauté privée pour les membres recherchant un environnement de soutien personnel.",
      rules:
        "Respectez la confidentialité. Ne partagez pas les conversations privées à l'extérieur du groupe.",
      visibility: prismaEnums.GroupVisibility.PRIVE,
    },
  ];

  const groups: Group[] = [];

  for (const data of groupData) {
    const group = await prisma.group.upsert({
      where: {
        name: data.name,
      },
      update: {
        theme: data.theme,
        desc: data.desc,
        rules: data.rules,
        visibility: data.visibility,
      },
      create: data,
    });

    groups.push(group);
  }

  console.log(`🌱 ${groups.length} groups created/updated successfully`);

  // ============================================================
  // GROUP MEMBERS
  // ============================================================

  console.log("🌱 Creating group memberships...");

  const anxietyGroup = getItem(groups, 0);
  const sleepGroup = getItem(groups, 1);
  const privateGroup = getItem(groups, 2);

  const sophie = getItem(users, 0);
  const thomas = getItem(users, 1);
  const emma = getItem(users, 2);
  const lucas = getItem(users, 3);
  const chloe = getItem(users, 4);
  const gabriel = getItem(users, 5);
  const lea = getItem(users, 6);
  const nathan = getItem(users, 7);
  const camille = getItem(users, 8);

  const membershipData = [
    // Soutien contre l'anxiété
    {
      userId: admin.userId,
      groupId: anxietyGroup.groupId,
      role: prismaEnums.GroupRole.MODERATEUR,
      requestStatus: prismaEnums.GroupRequestStatus.ACCEPTEE,
    },
    {
      userId: sophie.userId,
      groupId: anxietyGroup.groupId,
      role: prismaEnums.GroupRole.MODERATEUR,
      requestStatus: prismaEnums.GroupRequestStatus.ACCEPTEE,
    },
    {
      userId: thomas.userId,
      groupId: anxietyGroup.groupId,
      role: prismaEnums.GroupRole.MODERATEUR,
      requestStatus: prismaEnums.GroupRequestStatus.ACCEPTEE,
    },
    {
      userId: emma.userId,
      groupId: anxietyGroup.groupId,
      role: prismaEnums.GroupRole.MEMBRE,
      requestStatus: prismaEnums.GroupRequestStatus.ACCEPTEE,
    },
    {
      userId: nathan.userId,
      groupId: anxietyGroup.groupId,
      role: prismaEnums.GroupRole.MEMBRE,
      requestStatus: prismaEnums.GroupRequestStatus.ACCEPTEE,
    },

    // Meilleur sommeil
    {
      userId: admin.userId,
      groupId: sleepGroup.groupId,
      role: prismaEnums.GroupRole.MODERATEUR,
      requestStatus: prismaEnums.GroupRequestStatus.ACCEPTEE,
    },
    {
      userId: thomas.userId,
      groupId: sleepGroup.groupId,
      role: prismaEnums.GroupRole.MEMBRE,
      requestStatus: prismaEnums.GroupRequestStatus.ACCEPTEE,
    },
    {
      userId: lucas.userId,
      groupId: sleepGroup.groupId,
      role: prismaEnums.GroupRole.MEMBRE,
      requestStatus: prismaEnums.GroupRequestStatus.ACCEPTEE,
    },
    {
      userId: gabriel.userId,
      groupId: sleepGroup.groupId,
      role: prismaEnums.GroupRole.MEMBRE,
      requestStatus: prismaEnums.GroupRequestStatus.ACCEPTEE,
    },
    {
      userId: camille.userId,
      groupId: sleepGroup.groupId,
      role: prismaEnums.GroupRole.MEMBRE,
      requestStatus: prismaEnums.GroupRequestStatus.ACCEPTEE,
    },

    // Cercle de soutien privé
    {
      userId: admin.userId,
      groupId: privateGroup.groupId,
      role: prismaEnums.GroupRole.MODERATEUR,
      requestStatus: prismaEnums.GroupRequestStatus.ACCEPTEE,
    },
    {
      userId: sophie.userId,
      groupId: privateGroup.groupId,
      role: prismaEnums.GroupRole.MEMBRE,
      requestStatus: prismaEnums.GroupRequestStatus.ACCEPTEE,
    },
    {
      userId: chloe.userId,
      groupId: privateGroup.groupId,
      role: prismaEnums.GroupRole.MEMBRE,
      requestStatus: prismaEnums.GroupRequestStatus.ACCEPTEE,
    },
    {
      userId: lea.userId,
      groupId: privateGroup.groupId,
      role: prismaEnums.GroupRole.MEMBRE,
      requestStatus: prismaEnums.GroupRequestStatus.ACCEPTEE,
    },
    {
      userId: camille.userId,
      groupId: privateGroup.groupId,
      role: prismaEnums.GroupRole.NON_MEMBRE,
      requestStatus: prismaEnums.GroupRequestStatus.EN_ATTENTE,
    },
    {
      userId: lucas.userId,
      groupId: privateGroup.groupId,
      role: prismaEnums.GroupRole.NON_MEMBRE,
      requestStatus: prismaEnums.GroupRequestStatus.REFUSEE,
    },
  ];

  for (const data of membershipData) {
    await prisma.groupMember.upsert({
      where: {
        userId_groupId: {
          userId: data.userId,
          groupId: data.groupId,
        },
      },
      update: {
        role: data.role,
        requestStatus: data.requestStatus,
      },
      create: data,
    });
  }

  console.log(
    `🌱 ${membershipData.length} group memberships created/updated successfully`,
  );

  // ============================================================
  // JOURNAL ENTRIES
  // ============================================================

  console.log("🌱 Creating 30 days of journal entries...");

  const journalUser = getItem(users, 0);

  for (let i = 0; i < 30; i++) {
    const date = new Date();

    date.setHours(0, 0, 0, 0);
    date.setDate(date.getDate() - (29 - i));

    const journal = await prisma.journalEntry.upsert({
      where: {
        userId_date: {
          userId: journalUser.userId,
          date,
        },
      },
      update: {
        generalMood: Math.min(5, 2 + Math.floor(i / 10)),
        energyLevel: Math.min(5, 2 + Math.floor(i / 8)),
        sleepQuality: Math.min(5, 2 + Math.floor(i / 7)),
        stressLevel: Math.max(1, 5 - Math.floor(i / 8)),

        keyEvents:
          i % 3 === 0
            ? "J'ai eu une journée productive à l'école et j'ai passé un peu de temps dehors."
            : i % 3 === 1
              ? "J'ai eu une bonne conversation avec un ami."
              : "J'ai passé un moment tranquille à lire et à me détendre.",
        dailyGratitude:
          i % 2 === 0
            ? "Je suis reconnaissant envers les personnes qui me soutiennent."
            : "Je suis reconnaissant d'avoir eu un peu de temps tranquille aujourd'hui.",
      },
      create: {
        userId: journalUser.userId,
        date,

        generalMood: Math.min(5, 2 + Math.floor(i / 10)),
        energyLevel: Math.min(5, 2 + Math.floor(i / 8)),
        sleepQuality: Math.min(5, 2 + Math.floor(i / 7)),
        stressLevel: Math.max(1, 5 - Math.floor(i / 8)),

        keyEvents:
          i % 3 === 0
            ? "J'ai eu une journée productive à l'école et j'ai passé un peu de temps dehors."
            : i % 3 === 1
              ? "J'ai eu une bonne conversation avec un ami."
              : "J'ai passé un moment tranquille à lire et à me détendre.",

        dailyGratitude:
          i % 2 === 0
            ? "Je suis reconnaissant envers les personnes qui me soutiennent."
            : "Je suis reconnaissant d'avoir eu un peu de temps tranquille aujourd'hui.",
      },
    });

    // First activity
    const activity = getItem(activities, i % activities.length);

    await prisma.journalActivity.upsert({
      where: {
        journalId_activityId: {
          journalId: journal.journalId,
          activityId: activity.activityId,
        },
      },
      update: {},
      create: {
        journalId: journal.journalId,
        activityId: activity.activityId,
      },
    });

    // Second activity every other day
    if (i % 2 === 0) {
      const secondActivity = getItem(activities, (i + 1) % activities.length);

      await prisma.journalActivity.upsert({
        where: {
          journalId_activityId: {
            journalId: journal.journalId,
            activityId: secondActivity.activityId,
          },
        },
        update: {},
        create: {
          journalId: journal.journalId,
          activityId: secondActivity.activityId,
        },
      });
    }
  }

  console.log("🌱 30 journal entries created/updated successfully");

  // ============================================================
  // POSTS
  // ============================================================

  console.log("🌱 Creating posts...");

  const postTitles = [
    "Qu'est-ce qui vous aide à gérer les journées stressantes ?",
    "Comment maintenez-vous une bonne routine de sommeil ?",
    "Quelle est votre technique de relaxation préférée ?",
    "Comment gérez-vous une semaine difficile ?",
    "Les petites choses qui améliorent ma journée",
    "Qu'est-ce qui vous aide à vous sentir moins dépassé ?",
    "Comment décrochez-vous après le travail ?",
    "Partager une expérience positive",
    "À quoi ressemble une bonne routine du soir ?",
    "Comment restez-vous motivé ?",
  ];

  const posts: Post[] = [];

  for (let i = 0; i < 50; i++) {
    const group = getItem(groups, i % groups.length);
    const user = getItem(allUsers, (i + 1) % allUsers.length);

    const postId = seedUuid("00000000", i + 1);

    const title = `${getItem(postTitles, i % postTitles.length)} #${i + 1}`;

    const body =
      "Ceci est une publication de démonstration pour MindHarbor. " +
      "Elle permet de présenter du contenu communautaire réaliste, " +
      "les discussions et la pagination sans utiliser de données réelles.";

    const post = await prisma.post.upsert({
      where: {
        postId,
      },
      update: {
        userId: user.userId,
        groupId: group.groupId,
        title,
        body,
      },
      create: {
        postId,
        userId: user.userId,
        groupId: group.groupId,
        title,
        body,
      },
    });

    posts.push(post);
  }

  console.log(`🌱 ${posts.length} posts created/updated successfully`);

  // ============================================================
  // COMMENTS
  // ============================================================

  console.log("🌱 Creating comments...");

  for (let i = 0; i < 75; i++) {
    const post = getItem(posts, i % posts.length);
    const user = getItem(allUsers, (i + 2) % allUsers.length);

    const commentId = seedUuid("10000000", i + 1);

    const comment =
      i % 3 === 0
        ? "Merci d'avoir partagé ça. Je peux vraiment m'identifier à cette situation."
        : i % 3 === 1
          ? "C'est une perspective vraiment intéressante. Je pourrais essayer moi aussi."
          : "J'ai vécu une expérience similaire. Merci d'avoir lancé cette discussion.";

    await prisma.comment.upsert({
      where: {
        commentId,
      },
      update: {
        postId: post.postId,
        userId: user.userId,
        comment,
      },
      create: {
        commentId,
        postId: post.postId,
        userId: user.userId,
        comment,
      },
    });
  }

  console.log("🌱 75 comments created/updated successfully");

  // ============================================================
  // FAVORITES
  // ============================================================

  console.log("🌱 Creating favorite resources...");

  for (let i = 0; i < 20; i++) {
    const user = getItem(allUsers, (i + 1) % allUsers.length);

    const resource = getItem(resources, i % resources.length);

    await prisma.favorite.upsert({
      where: {
        UserId_resourceId: {
          UserId: user.userId,
          resourceId: resource.resourceId,
        },
      },
      update: {},
      create: {
        UserId: user.userId,
        resourceId: resource.resourceId,
      },
    });
  }

  console.log("🌱 20 favorites created/updated successfully");

  // ============================================================
  // MESSAGES
  // ============================================================

  console.log("🌱 Creating messages...");

  const messageTexts = [
    "Salut ! Comment vas-tu ?",
    "Merci pour ton message !",
    "J'ai trouvé cette ressource vraiment utile.",
    "J'espère que tu passes une bonne journée.",
    "Ça semble être une excellente idée.",
  ];

  for (let i = 0; i < 20; i++) {
    const sender = getItem(allUsers, i % allUsers.length);

    const recipient = getItem(allUsers, (i + 1) % allUsers.length);

    const messageId = seedUuid("20000000", i + 1);

    const readReceipt =
      i % 3 === 0
        ? prismaEnums.MessageReadReceipt.SENT
        : prismaEnums.MessageReadReceipt.READ;

    await prisma.message.upsert({
      where: {
        messageId,
      },
      update: {
        senderId: sender.userId,
        recipientId: recipient.userId,
        message: getItem(messageTexts, i % messageTexts.length),
        readReceipt,
      },
      create: {
        messageId,
        senderId: sender.userId,
        recipientId: recipient.userId,
        message: getItem(messageTexts, i % messageTexts.length),
        readReceipt,
      },
    });
  }

  console.log("🌱 20 messages created/updated successfully");

  // ============================================================
  // REPORTS
  // ============================================================

  console.log("🌱 Creating reports...");

  const reportCategories = [
    prismaEnums.ReportCategory.INAPPROPRIE,
    prismaEnums.ReportCategory.SPAM,
    prismaEnums.ReportCategory.INQUIETANT,
  ];

  const reportStatuses = [
    prismaEnums.ReportStatus.EN_ATTENTE,
    prismaEnums.ReportStatus.EN_COURS_DE_REVISION,
    prismaEnums.ReportStatus.RESOLUE,
    prismaEnums.ReportStatus.REJETEE,
  ];

  for (let i = 0; i < 10; i++) {
    const post = getItem(posts, i);
    const user = getItem(allUsers, (i + 3) % allUsers.length);

    const reportId = seedUuid("30000000", i + 1);

    const category = getItem(reportCategories, i % reportCategories.length);

    const status = getItem(reportStatuses, i % reportStatuses.length);

    await prisma.report.upsert({
      where: {
        reportId,
      },
      update: {
        postId: post.postId,
        userId: user.userId,
        category,
        status,
      },
      create: {
        reportId,
        postId: post.postId,
        userId: user.userId,
        category,
        status,
      },
    });
  }

  console.log("🌱 10 reports created/updated successfully");

  // ============================================================
  // SUMMARY
  // ============================================================

  console.log("\n========================================");
  console.log("🌱 SEED COMPLETED SUCCESSFULLY");
  console.log("========================================");
  console.log(`Users:            ${allUsers.length}`);
  console.log(`Activities:       ${activities.length}`);
  console.log(`Resources:        ${resources.length}`);
  console.log(`Groups:           ${groups.length}`);
  console.log("Journal entries:  30");
  console.log(`Posts:             ${posts.length}`);
  console.log("Comments:          75");
  console.log("Favorites:        20");
  console.log("Messages:         20");
  console.log("Reports:          10");
  console.log("========================================");

  console.log("\nAdmin credentials:");
  console.log("Email:    admin@mindharbor.com");
  console.log("Password: Admin123");
}

// ============================================================
// EXECUTION
// ============================================================

main()
  .catch((error: unknown) => {
    console.error("Seed failed:");

    if (error instanceof Error) {
      console.error(error.message);
      console.error(error.stack);
    } else {
      console.error(error);
    }

    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
