@baseUrl = http://localhost:5173/api/v1

### ============================================================
### LOGIN
### ============================================================

### Login - valid credentials
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "TestPassword123"
}

# "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJmZDU1ZjQ3LThkMjctNDZkYy04NzI0LWMxZWQ4ZTgwMTUxZiIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzg2ODIyMzIxLCJleHAiOjE3ODY4MjMyMjF9.0XOYzJvZKQDzCeZD_trYtzCVmclvEY1jbbvYFQsieQY",

# "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJmZDU1ZjQ3LThkMjctNDZkYy04NzI0LWMxZWQ4ZTgwMTUxZiIsImlhdCI6MTc4NjgyMjMyMSwiZXhwIjoxNzg3NDI3MTIxfQ.nkmuzKqbjH7_UDRUYQ6530SPglTH1tb6LXajzL3CFzg"



### Login - wrong password
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "WrongPassword123"
}


### Login - unknown email
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "doesnotexist@example.com",
  "password": "TestPassword123"
}


### Login - invalid email
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "not-an-email",
  "password": "TestPassword123"
}


### Login - missing password
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@example.com"
}


### Login - missing email
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "password": "TestPassword123"
}


### Login - empty body
POST {{baseUrl}}/auth/login
Content-Type: application/json

{}
