Table User {
  userId uuid [primary key]

}

Table JournalEntry {
  journalId uuid [primary key, not null]
  userId uuid [ref: > User.userId, not null]

  generalMood int [check: `generalMood 1 >= and generalMood <= 5`, not null]
  energyLevel int [check: `energyLevel 1 >= and energyLevel <= 5`, not null]
  sleepQuality int [check: `sleepQuality 1 >= and sleepQuality <= 5`, not null]
  stessLevel int [check: `stessLevel 1 >= and stessLevel <= 5`, not null]
  keyEvents String [not null]
  dailyGratitude String

  createdAt date [default: `today()`, not null]
  updatedAt datetime [default: `now()`]

  // a journal entry can only be made once a day
  indexes {
    (userId, createdAt) [unique]
  }
}

Table Activity {
  activityId uuid [primary key]
  name String [not null, unique]
  desc String [not null]

  createdAt datetime [default: `now()`]
}

// Junction table between JournalEntry & Activity
Table JournalEntriesActvities {
    journalId uuid [primary key, ref: > JournalEntry.journalId]
    activityId uuid [primary key, ref: > Activity.activityId]
}

Table Resource {
  resourceId uuid [primary key]

  name String [not null, unique]
  category ResourceCategoryEnum [not null]
  type ResourceTypeEnum [not null]
  duration float [not null]
  level int [check: `level >= 0`, not null]

  createdAt datetime [default: `now()`]
  updatedAt datetime [default: `now()`]
}

Enum ResourceCategoryEnum {
    ANXIETY
    SLEEP
    RELATIONSHIP
    WORK
    GRIEF
}

Enum ResourceTypeEnum {
    ARTICLES
    EXERCICES
    PRACTICAL_SHEET
    AUDIO_LINK
    VIDEO_LINK
}

// Junction Table between User and Resource to add a resource to favorites
Table Favorite {
    userId uuid [primary key, ref: > User.userId]
    resource uuid [primary key, ref: > Resource.resourceId]
}

Table Group {
  groupId uuid [primary key]

  name String [not null]
  theme String [not null]
  desc String [not null]
  rules String [not null]
  visibility GroupVisibilityEnum [not null]

  createdAt datetime [default: `now()`]
  updatedAt datetime [default: `now()`]
}

Enum GroupVisibilityEnum {
    PUBLIC
    PRIVE
}

Table GroupMembershipRequest {
    groupMemberShipId uuid [primary key]
    groupId uuid [ref: > Group.groupId]
    userId uuid [ref: > User.userId]

    status GroupRequestStatusEnum

    createdAt datetime [default: `now()`]
    updatedAt datetime [default: `now()`]

    // a user cannot have multiple request for the same group at the same time
    indexes {
        (groupId, userId) [unique] // this syntax prevents a user from creating multiple request at the same however if the request has been refused a user wont be able to request again; will need to be fixed in the actual DB schema
    }
}

Enum GroupRequestStatusEnum {
    EN_ATTENTE
    ACCEPTEE
    REFUSEE
}

Table GroupMember {
  groupMemberId uuid [primary key, unique]
}

Table Post {
  postId uuid [primary key, unique]
}

Table Comment {
  commentId uuid [primary key, unique]
}

Table Message {
  messageId uuid [primary key, unique]
}

Table Report {
 reportId uuid [primary key, unique]
}

Table RefreshToken {
 refreshTokenId uuid [primary key, unique]
}
